### ISSUE TITLE
爬虫内容

### ISSUE THREAD

**Issue by csy1998** [Chanran/tianyancha_spider#2]
您好，我想请问一下爬出来的内容保存到了哪里？谢谢

**Comment by Chanran** [comment]
![image](https://user-images.githubusercontent.com/11496220/28024937-9a00b222-65c4-11e7-95a4-ca78b26c79e2.png)
代码量不多，可以直接看源码，这个项目基本废弃不维护的，因为隔一段时间，天眼查的网站接口又会变化的。
